### ISSUE TITLE
🔍 search creator by zip code page

### ISSUE THREAD

**Issue by mohsenxad** [lettucesocial/com-lettucesocial-customer-panel#10]
### 🔍 search creator by zip code page

![image](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/3274057/a569e9c9-e5be-4c84-ac73-0a4e3cdf33cd)

![Image](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/3274057/b5d2ea27-4e1c-409d-a89c-1bc218e518ee)

After an accurate zip code is searched
In the top search box, the user will see the name of the city and state associated with the
zip code they entered. Format is [City name], [State name]
note that state note uses the convention of two letter for states that can be found in the
below github repo
Python Dictionary for State Abbreviations: This resource provides a Python dictionary to
translate US states to two-letter codes. It includes mappings for all 50 states, as well as
territories like American Samoa, Guam, and Puerto Rico. The dictionary is structured in a
way that you can easily look up the abbreviation by the full state name. Python Dictionary
for State Abbreviations Gi st
https://gist.github.com/
User can see an image, and information about the creators who are in the same zip code
the user entered
Page 4 of 17
User can scroll, up and down to see more creators (if there are more than one)
User can use the back or home buttons at the bottom ribbon to get back to the home page
When user clicks on the Instagram handle or the Instagram icon, it opens creators
Instagram profil e
The location icon and name are not clickable
When user clicks on Request Collaboration button, they go to the next page

**Comment by maxzad** [comment]
@mohsenxad @price76 

Home Page:

- The LettuceSocial Logo is too large compared to the design.
- The background color is gradient, green with a shade of yellow more towards the bottom - between the two colors of green (#9EDA9E) and yellow (#FDD54F)
- The Zip code verification does not work - when I enter a random number like 9182872772 - it takes me to the page to fill out the form to be informed when a new creator is joined in this Zip code, while no such Zip code exists. It should show the Zip code error message

Search Results Page:
- Not showing the search box at the top of the page

**Comment by maxzad** [comment]
tested - done
