### ISSUE TITLE
🎯 validate zipcode in search view

### ISSUE THREAD

**Issue by mohsenxad** [lettucesocial/com-lettucesocial-customer-panel#11]
### 🎯 validate zip code in search view

![image](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/3274057/3cca7d07-21ad-47d3-b667-95d4df288c8a)

Validate user input against one the following databases of US zip codes.
Blakek/us-zips: This database lists US ZIP codes and their geolocations based on the US
Census Bureau's ZIP Code Tabulation Areas (ZCTAs). The data includes latitude and
longitude for each ZIP code and is regularly updated with Census Bureau data. The
database is available in different formats: Object, Array, Key/value, and Map. Blakek/uszips GitHub Repository
https://github.com/blakek/us-zips

MacHu-GWU/uszipcode-project: This is a Python programmable database that includes
comprehensive information, such as address, postal, geography, and demographic
statistics. It contains 42,724 ZIP codes, including types like STANDARD, PO Box, UNIQUE,
and MILITARY. The data is sourced from data.census.gov. MacHu-GWU/uszipcode-project
GitHub Repository
https://github.com/MacHu-GWU/uszipcode-project

VinceG/US-Zip-Codes: This database provides an updated list of nearly 42,000 US ZIP
Codes from 62 different states (including territories and military). The data is structured
as a MySQL dump file containing a table 'zip_code' with columns for ZIP code, city,
county, and state. VinceG/US-Zip-Codes GitHub Repository
https://github.com/VinceG/US-Zip-Codes

**Comment by maxzad** [comment]
tested - done
