### ISSUE TITLE
📝collect business information page without creator

### ISSUE THREAD

**Issue by mohsenxad** [lettucesocial/com-lettucesocial-customer-panel#12]
### 📝collect business information page without creator

![image](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/3274057/04730803-d67c-4364-9299-5d2743d4e574)

![image](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/3274057/af12afc2-76f2-4833-8662-5c3097653088)

This page is shown when user input delivers no results.
Both back and Home buttons at the bottom ribbon takes user to the home page
Name field only accepts characters and no numbers
Email field needs email validation code (use javascript code provided in Git)
Mobile field needs mobile validation code (use javascript code provided in Git)
Business Name field can use any input both char and number
Clicked on "Get Notified" > go to page 5
----
Send the information collected in this form + the zip code entered by the user to the
following email addresses:

**Comment by maxzad** [comment]
@mohsenxad 
based on the design change we agreed - about the top search bar - this page needs to also incorporate that change.

currently doesn't show the search bar 

also should show 0 results found in [zip code]


![Lettucesocial  Business](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/19561243/814c780a-29c3-45f1-81fb-bcb5b193fc37)

**Comment by maxzad** [comment]
@mohsenxad 

where does the result of the form submission go?

not telegram! no email either

either add it to telegram or email to max@lettucesocial.com

**Comment by maxzad** [comment]
@mohsenxad 

- the result is not sent to Telegram - that is fixed - thanks

What is not fixed is the what I referred to in my first comment:

based on the design change we agreed - about the top search bar - this page needs to also incorporate that change.

1) currently doesn't show the search bar - should show the search bar

also should show 0 results found in **[zip code]**



![8BA848DA-BC15-4FD5-8F11-34087B019F21_4_5005_c](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/19561243/4a0f1298-61e8-4f9c-933c-a9006a1aa861)

**Comment by maxzad** [comment]
@mohsenxad 

why did you change the bold to unbold and made the unbold, bold?

please update

![Lettucesocial  Business 2](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/19561243/e9553cf4-a23f-4a99-9a4f-b2142bfaf990)

**Comment by maxzad** [comment]
tested - done
