### ISSUE TITLE
😊 select collaboration plane

### ISSUE THREAD

**Issue by mohsenxad** [lettucesocial/com-lettucesocial-customer-panel#13]
### 😊 select collaboration plane

![image](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/3274057/1e7ba61a-e991-4c86-a6c8-10e8ee999050)

When user clicks on "Request Collaboration" on any of the creators - they land on this
page
At the top left, the user will see a small avatar of the creator image, their First name and
First letter of their last name. Underneath their Instagram handle
NOTE: None of these are clickable/linked
User can select from any of the 3 collaboration packages
Buttons with $ pricing are clickable

**Comment by mohsenxad** [comment]
HARVEST plane ux

![image](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/3274057/a656c1e7-c0d0-4818-a1e3-d4f7e0490dd5)

**Comment by maxzad** [comment]
tested
