### ISSUE TITLE
📄 create collaboration invoice

### ISSUE THREAD

**Issue by mohsenxad** [lettucesocial/com-lettucesocial-customer-panel#14]
### 📄 create collaboration invoice

![Image](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/3274057/038934a3-8c77-4b09-9e93-a0497d10ddce)

After any of the packages are clicked - on the price button
The selected package will show at the top under "Package Details"
Just for demonstration, I show Grow
the price button is not clickable here
only clickable button is the Pay $X
the number $10 is dynamic
should be calculated as 10% of the value of the selected package
(Plant > 10% of $70 = $7)
(Grow > 10% of $100 = $10)
(Harvest > 10% of $250 = $25)

**Comment by maxzad** [comment]
tested
