### ISSUE TITLE
🛒 collect business information after payment

### ISSUE THREAD

**Issue by mohsenxad** [lettucesocial/com-lettucesocial-customer-panel#15]
### 🛒 collect business information after payment

![Image](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/3274057/acec1c03-0e23-414b-bd9e-2d11d87076c5)

![Image](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/3274057/b8964496-853c-4c83-9000-bea3d9fa76bc)

After successful payment of 10% deposit
we collect the following information
Name field only accepts characters and no numbers
Email field needs email validation code (use javascript code provided in Git)
Mobile field needs mobile validation code (use javascript code provided in Git)
Business Name field can use any input both char and number
Send the information collected in this form + the zip code entered by the user to the

**Comment by maxzad** [comment]
embedded this information in the payment page, so no need to build a separate page.
