### ISSUE TITLE
question - naming the creators' profile pictures

### ISSUE THREAD

**Issue by maxzad** [lettucesocial/com-lettucesocial-customer-panel#3]
we are going to provide creator images. 
is there a preferred naming convention?

example
we can do [Instagram handle.png]
example > zadehmax.png

**Comment by mohsenxad** [comment]
@maxzad 
in admin panel website, in creator list, for each creator we have an uniq id that we can use for file name.
all files should have same extension. like .png or .jpg 

![image](https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/3274057/4de99f8c-58ef-40cb-bfa7-8f7b72e10abe)

**Comment by maxzad** [comment]
@mohsenxad We agreed via Telegram chat that we would not be using the unique ID as a naming convention for the creator profile pics since we don't have all the ~200 creators on the admin panel; hence, not all have this unique ID.

We agreed instead to use the following convention for naming.

[instagram handle].png
