### ISSUE TITLE
🖼 UX of search creator with zip code

### ISSUE THREAD

**Issue by mohsenxad** [lettucesocial/com-lettucesocial-customer-panel#4]
🖼 UX of search creator with zip code

upload UX in this issue

**Comment by maxzad** [comment]
@mohsenxad see attachments.

1) Zip file includes each view

2) PDF includes notes related to each page

If you don't have Canva, please sign up. It is free, and I can add you to my account. The same goes 


[LettuceSocial Business Mobile App Design-V1.zip](https://github.com/lettucesocial/com-lettucesocial-customer-panel/files/13310677/LettuceSocial.Business.Mobile.App.Design-V1.zip)
[LettuceSocial Business Mobile App Design V1-PDF.pdf](https://github.com/lettucesocial/com-lettucesocial-customer-panel/files/13310678/LettuceSocial.Business.Mobile.App.Design.V1-PDF.pdf)
for the UI Developer.
