### ISSUE TITLE
Setup HotJar for monitoring user behavior and improve conversion

### ISSUE THREAD

**Issue by maxzad** [lettucesocial/com-lettucesocial-customer-panel#41]
@mohsenxad 
We have an old hotjar account under flekswork
Let me know if you want me to create a new one for LettuceSocial or you can use the old one.

**Comment by mohsenxad** [comment]
@maxzad 
this item depend on #34 to use https for business panel

**Comment by mohsenxad** [comment]
@maxzad 
test the below url 

[https://lettucesocial.sentry.io/](https://lettucesocial.sentry.io/)

**Comment by maxzad** [comment]
@mohsenxad I don't understand how Sentry relates to HotJar

HotJar's main value here is "session recording" where we can see exactly where users click and move and scroll, and stop and drop off the funnel

https://www.youtube.com/watch?v=ztpUdJQu2kY

Based on what I watched on Sentry, it is more of a dashboard (a little like what we used to get from MixPanel)

**Comment by mohsenxad** [comment]
@maxzad 
send invitation to hotjar panel

**Comment by maxzad** [comment]
@mohsenxad 

Please send invite to max@flekswork.com

**Comment by maxzad** [comment]
tested - done
