### ISSUE TITLE
Previous page not loading if user clicks back from the Stripe payment page

### ISSUE THREAD

**Issue by maxzad** [lettucesocial/com-lettucesocial-customer-panel#47]
See video

https://www.loom.com/share/ca5496188da84ea6a23aa99efec199d1?sid=5e71e631-e1d2-45f4-9461-58a1b215b8c1

**Comment by maxzad** [comment]
@mohsenxad 
not fixed. Same issue exists.

**Comment by mohsenxad** [comment]
@maxzad 

if you installed the app (share to home)
remove it and start from url in safari

**Comment by maxzad** [comment]
tested - done
