### ISSUE TITLE
add hello.lettucesocial.com to mailgun domains

### ISSUE THREAD

**Issue by mohsenxad** [lettucesocial/com-lettucesocial-customer-panel#51]
set hello.lettucesocial.com config to wix dns settings

there is some configs that we need to add to dns 
these configs exist in 

https://app.mailgun.com/app/sending/domains/hello.lettucesocial.com

_Originally posted by @mohsenxad in https://github.com/lettucesocial/com-lettucesocial-customer-api/issues/9

**Comment by maxzad** [comment]
@mohsenxad we need to do this in a meeting via screen share

I could do a couple of them but a few others I wans't able to do/didn't want to mess things up.

**Comment by maxzad** [comment]
tested - done
