### ISSUE TITLE
store zip codes users enter in the zip code field and click search

### ISSUE THREAD

**Issue by maxzad** [lettucesocial/com-lettucesocial-customer-panel#55]
in our business owner's app, when a user enters a zip code and clicks search, we store the zip code so we can see which zip codes we get the most search.

**Comment by mohsenxad** [comment]
i create a custom dimension on GA
it takes time to collect data with this dimension and will show the result in reports

**Comment by mohsenxad** [comment]
@maxzad  i share the GA report with you related to this issue

**Comment by maxzad** [comment]
tested - done
