### ISSUE TITLE
Remove Cash App Pay from the payment methods in Stripe

### ISSUE THREAD

**Issue by maxzad** [lettucesocial/com-lettucesocial-customer-panel#72]
Remove this option 

<img width="311" alt="image" src="https://github.com/lettucesocial/com-lettucesocial-customer-panel/assets/19561243/50a5d0ec-5126-4dfb-8d37-1d0184d3f8ca">

**Comment by mohsenxad** [comment]
@maxzad 
i didn't set any parameter for showing this item.🤔
it seems there is a setting option in stripe panel

**Comment by maxzad** [comment]
@mohsenxad 
I removed it at the account level. All good.
